### ISSUE TITLE
Outdated deps etc

### ISSUE THREAD

**Issue by aapit** [grrr-amsterdam/classifier-prototype#5]
Hey,

Is this project still relevant?
If not, let's archive it?
If it is, could you take a look at the CI status of the `greenkeeper/initial` branch?
https://travis-ci.org/grrr-amsterdam/classifier-prototype/branches
it seems this one is quite outdated by now.

**Comment by harmenjanssen** [comment]
Honestly I'm not sure. It's been a solo effort by @larixk 

That being said, why would you archive it? It's here if you ever want to look at it. I wouldn't bother keeping it green though, it worked fine with the declared versions at the time and since we're not going to actively maintain it I don't see the point.

I would just keep it as reference material.

**Comment by aapit** [comment]
Okidoki 👍🏼
